#!/bin/sh
#    gus.mb, an open source flow solver.
#    Copyright (C) 2016 Hiromasa Kato <hiromasa at gmail.com>
#
#    This file is part of gus.mb.
#
#    gus.mb is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    gus.mb is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

MPIType() {
	if test "x$OMPI_COMM_WORLD_RANK" != "x"; then
		echo "OPENMPI"
	elif test "x$PMI_RANK" != "x"; then
		echo "INTELMPI"
	else
		echo "NOMPI"
	fi
}

GetMyRank() {
	mpitype=`MPIType`
	if test $mpitype = "OPENMPI"; then
		echo $OMPI_COMM_WORLD_RANK
	elif test $mpitype = "INTELMPI"; then
		echo $PMI_RANK
	else
		echo 0
	fi
}

GetWorldSize() {
	case `MPIType` in
	OPENMPI)
		echo $OMPI_COMM_WORLD_SIZE
		;;
	INTELMPI)
		echo $PMI_SIZE
		;;
	*)
		echo 1
		;;
	esac
}

D=`dirname $0`

infile=$1
stem=`echo $infile | sed 's/\.in$//'`
configfile=$stem.config

echo $D $infile $configfile

commsize=`GetWorldSize`
echo "World communicator size = $commsize"

myrank=`GetMyRank`
echo "My rank = $myrank"

if test $myrank = 0; then

	$D/P $D/GenerateBCs.py $infile $commsize > $configfile
	if test ! $? = 0; then
		exit $?
	fi
	$D/P $D/SolverSetup.py $infile
	if test ! $? = 0; then
		exit $?
	fi
fi

LD_LIBRARY_PATH=$D:$LD_LIBRARY_PATH $D/Solver $configfile $2

